-- MySQL Script generated by MySQL Workbench
-- Mon May  8 23:40:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDM` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDM` ;

-- -----------------------------------------------------
-- Table `LittleLemonDM`.`deliverystatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`deliverystatus` (
  `deliveryStatusID` INT NOT NULL,
  `deliveryDate` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`deliveryStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`delivery` (
  `deliveryID` INT NOT NULL,
  `deliveryCost` DECIMAL NULL,
  `deliveryStatusID` INT NOT NULL,
  PRIMARY KEY (`deliveryID`),
  INDEX `fk_delivery_deliverystatus1_idx` (`deliveryStatusID` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_deliverystatus1`
    FOREIGN KEY (`deliveryStatusID`)
    REFERENCES `LittleLemonDM`.`deliverystatus` (`deliveryStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`cuisine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`cuisine` (
  `cuisineID` INT NOT NULL,
  `cuisineName` VARCHAR(45) NULL,
  `starter` VARCHAR(45) NULL,
  `desert` VARCHAR(45) NULL,
  `drink` VARCHAR(45) NULL,
  `side` VARCHAR(45) NULL,
  PRIMARY KEY (`cuisineID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`menu` (
  `menuID` INT NOT NULL,
  `courseName` VARCHAR(45) NULL,
  `cost` DECIMAL NULL,
  `cuisineID` INT NOT NULL,
  PRIMARY KEY (`menuID`),
  INDEX `fk_menu_cuisine1_idx` (`cuisineID` ASC) VISIBLE,
  CONSTRAINT `fk_menu_cuisine1`
    FOREIGN KEY (`cuisineID`)
    REFERENCES `LittleLemonDM`.`cuisine` (`cuisineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`location` (
  `locationID` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `postalCode` INT NULL,
  `country` VARCHAR(45) NULL,
  `countryCode` VARCHAR(45) NULL,
  PRIMARY KEY (`locationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`customer` (
  `customerID` INT NOT NULL,
  `customerName` VARCHAR(45) NULL,
  `phoneNo` INT NULL,
  `email` VARCHAR(45) NULL,
  `locationID` INT NOT NULL,
  PRIMARY KEY (`customerID`),
  INDEX `fk_customer_location_idx` (`locationID` ASC) VISIBLE,
  UNIQUE INDEX `phoneNo_UNIQUE` (`phoneNo` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_customer_location`
    FOREIGN KEY (`locationID`)
    REFERENCES `LittleLemonDM`.`location` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`order` (
  `orderID` INT NOT NULL,
  `orderDate` DATE NULL,
  `quantity` VARCHAR(45) NULL,
  `discount` VARCHAR(45) NULL,
  `totalCost` VARCHAR(45) NULL,
  `deliveryID` INT NOT NULL,
  `menuID` INT NOT NULL,
  `customerID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_order_delivery1_idx` (`deliveryID` ASC) VISIBLE,
  INDEX `fk_order_menu1_idx` (`menuID` ASC) VISIBLE,
  INDEX `fk_order_customer1_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `fk_order_delivery1`
    FOREIGN KEY (`deliveryID`)
    REFERENCES `LittleLemonDM`.`delivery` (`deliveryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_menu1`
    FOREIGN KEY (`menuID`)
    REFERENCES `LittleLemonDM`.`menu` (`menuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `LittleLemonDM`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`staff` (
  `staffID` INT NOT NULL,
  `staffName` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  PRIMARY KEY (`staffID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
