-- MySQL Script generated by MySQL Workbench
-- Mon May  8 20:11:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDM` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDM` ;

-- -----------------------------------------------------
-- Table `LittleLemonDM`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`Customer` (
  `customerID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phoneNo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phoneNo_UNIQUE` (`phoneNo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`Staff` (
  `staffID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `salary` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`Booking` (
  `bookingID` INT NOT NULL,
  `bookingDate` DATE NOT NULL,
  `tableNo` VARCHAR(45) NOT NULL,
  `Customer_customerID` INT NOT NULL,
  `Staff_staffID` INT NOT NULL,
  PRIMARY KEY (`bookingID`),
  INDEX `fk_Booking_Customer1_idx` (`Customer_customerID` ASC) VISIBLE,
  INDEX `fk_Booking_Staff1_idx` (`Staff_staffID` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_Customer1`
    FOREIGN KEY (`Customer_customerID`)
    REFERENCES `LittleLemonDM`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Staff1`
    FOREIGN KEY (`Staff_staffID`)
    REFERENCES `LittleLemonDM`.`Staff` (`staffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`Menu` (
  `menuID` INT NOT NULL,
  `menuType` VARCHAR(45) NULL,
  `menuItem` VARCHAR(45) NULL,
  `price` DECIMAL NULL,
  PRIMARY KEY (`menuID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`Order` (
  `orderID` INT NOT NULL,
  `date` DATE NULL,
  `quantity` VARCHAR(45) NULL,
  `totalCost` VARCHAR(45) NULL,
  `Customer_customerID` INT NOT NULL,
  `Menu_menuID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_Customer1_idx` (`Customer_customerID` ASC) VISIBLE,
  INDEX `fk_Order_Menu1_idx` (`Menu_menuID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_customerID`)
    REFERENCES `LittleLemonDM`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Menu1`
    FOREIGN KEY (`Menu_menuID`)
    REFERENCES `LittleLemonDM`.`Menu` (`menuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDM`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDM`.`OrderStatus` (
  `deliveryID` INT NOT NULL,
  `deliveryDate` DATE NULL,
  `status` VARCHAR(45) NULL,
  `Order_orderID` INT NOT NULL,
  PRIMARY KEY (`deliveryID`),
  INDEX `fk_OrderStatus_Order1_idx` (`Order_orderID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderStatus_Order1`
    FOREIGN KEY (`Order_orderID`)
    REFERENCES `LittleLemonDM`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
